version: 1
build:
  main: cmd/cantod
  binary: cantod
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 1000000000000token
  - 1000000000000uatom
  - 1000000000000stake
  - 200000000000000000000acanto
- name: bob
  coins:
  - 1000000000000stake

faucet:
  name: bob
  coins:
  - 10acanto
  host: 0.0.0.0:4500
genesis:
  app_state:
    coinswap:
      standard_denom: acanto
      params:
        whitelisted_denoms:
          - uatom
          - stake
    crisis:
      constant_fee:
        denom: acanto
    evm:
      params:
        evm_denom: acanto
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: acanto
    mint:
      params:
        mint_denom: acanto
    staking:
      params:
        bond_denom: acanto
  chain_id: cantod_9000-1
validators:
- name: alice
  bonded: 100000000000000000000acanto
  app:
    evm-rpc:
      address: 0.0.0.0:8545
      ws-address: 0.0.0.0:8546
  home: $HOME/.cantod
