// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: canto/liquidstaking/v1/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// TBD
type Params struct {
	LiquidBondDenom string `protobuf:"bytes,1,opt,name=liquid_bond_denom,json=liquidBondDenom,proto3" json:"liquid_bond_denom,omitempty"`
	// minimum insurance percentage for liquid staking
	// should be larger than maximum slashable percentage within an epoch
	MinInsurancePercentage github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=min_insurance_percentage,json=minInsurancePercentage,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"min_insurance_percentage"`
	// size of one liquid staking chunk in CANTO
	ChunkSize github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=chunk_size,json=chunkSize,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"chunk_size"`
	// maximum number of chunks to be alive
	MaxAliveChunk github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=max_alive_chunk,json=maxAliveChunk,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"max_alive_chunk"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_22e120e419446f1d, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetLiquidBondDenom() string {
	if m != nil {
		return m.LiquidBondDenom
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "canto.liquidstaking.v1.Params")
}

func init() {
	proto.RegisterFile("canto/liquidstaking/v1/params.proto", fileDescriptor_22e120e419446f1d)
}

var fileDescriptor_22e120e419446f1d = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4a, 0xc3, 0x30,
	0x18, 0xc7, 0xdb, 0x29, 0x83, 0x15, 0x64, 0x58, 0x64, 0x14, 0x0f, 0x9d, 0x28, 0x88, 0x08, 0x6b,
	0x99, 0x3e, 0x81, 0xdd, 0x2e, 0x3b, 0x28, 0x63, 0x8a, 0x07, 0x11, 0x42, 0x96, 0x86, 0x2e, 0x74,
	0xf9, 0x52, 0x9b, 0xb4, 0xce, 0x3d, 0x85, 0x2f, 0x25, 0xec, 0xb8, 0xa3, 0x78, 0x18, 0xb2, 0xbd,
	0x88, 0x24, 0x9b, 0xa2, 0xde, 0xf4, 0x94, 0xe4, 0xcb, 0xff, 0xff, 0xfb, 0x0e, 0x3f, 0xe7, 0x88,
	0x60, 0x50, 0x22, 0x1c, 0xb3, 0x87, 0x82, 0xc5, 0x52, 0xe1, 0x94, 0x41, 0x12, 0x96, 0xed, 0x30,
	0xc3, 0x39, 0xe6, 0x32, 0xc8, 0x72, 0xa1, 0x84, 0xdb, 0x30, 0xa1, 0xe0, 0x47, 0x28, 0x28, 0xdb,
	0xfb, 0x7b, 0x89, 0x48, 0x84, 0x89, 0x84, 0xfa, 0xb6, 0x4e, 0x1f, 0xbe, 0x54, 0x9c, 0x6a, 0xdf,
	0xd4, 0xdd, 0x53, 0x67, 0x77, 0x5d, 0x42, 0x43, 0x01, 0x31, 0x8a, 0x29, 0x08, 0xee, 0xd9, 0x07,
	0xf6, 0x49, 0x6d, 0x50, 0x5f, 0x7f, 0x44, 0x02, 0xe2, 0xae, 0x1e, 0xbb, 0x23, 0xc7, 0xe3, 0x0c,
	0x10, 0x03, 0x59, 0xe4, 0x18, 0x08, 0x45, 0x19, 0xcd, 0x09, 0x05, 0x85, 0x13, 0xea, 0x55, 0x74,
	0x25, 0x0a, 0x66, 0x8b, 0xa6, 0xf5, 0xb6, 0x68, 0x1e, 0x27, 0x4c, 0x8d, 0x8a, 0x61, 0x40, 0x04,
	0x0f, 0x89, 0x90, 0x5c, 0xc8, 0xcd, 0xd1, 0x92, 0x71, 0x1a, 0xaa, 0xa7, 0x8c, 0xca, 0xa0, 0x4b,
	0xc9, 0xa0, 0xc1, 0x19, 0xf4, 0x3e, 0x71, 0xfd, 0x2f, 0x9a, 0x7b, 0xe9, 0x38, 0x64, 0x54, 0x40,
	0x8a, 0x24, 0x9b, 0x52, 0x6f, 0xeb, 0xcf, 0xec, 0x1e, 0xa8, 0x41, 0xcd, 0x10, 0xae, 0xd9, 0x94,
	0xba, 0xb7, 0x4e, 0x9d, 0xe3, 0x09, 0xc2, 0x63, 0x56, 0x52, 0x64, 0xc6, 0xde, 0xf6, 0xbf, 0x98,
	0x3b, 0x1c, 0x4f, 0x2e, 0x34, 0xa5, 0xa3, 0x21, 0xd1, 0xfd, 0x6c, 0xe9, 0xdb, 0xf3, 0xa5, 0x6f,
	0xbf, 0x2f, 0x7d, 0xfb, 0x79, 0xe5, 0x5b, 0xf3, 0x95, 0x6f, 0xbd, 0xae, 0x7c, 0xeb, 0x2e, 0xfa,
	0x06, 0xec, 0x68, 0x35, 0xad, 0x2b, 0xaa, 0x1e, 0x45, 0x9e, 0x6e, 0x5e, 0x37, 0x54, 0x2a, 0xa0,
	0xaa, 0x55, 0x9e, 0x69, 0x95, 0x93, 0x5f, 0x76, 0xcd, 0xc2, 0x61, 0xd5, 0xc8, 0x3a, 0xff, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xfa, 0xe4, 0x87, 0x36, 0x01, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxAliveChunk.Size()
		i -= size
		if _, err := m.MaxAliveChunk.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.ChunkSize.Size()
		i -= size
		if _, err := m.ChunkSize.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MinInsurancePercentage.Size()
		i -= size
		if _, err := m.MinInsurancePercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.LiquidBondDenom) > 0 {
		i -= len(m.LiquidBondDenom)
		copy(dAtA[i:], m.LiquidBondDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.LiquidBondDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LiquidBondDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.MinInsurancePercentage.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.ChunkSize.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxAliveChunk.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidBondDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidBondDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinInsurancePercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinInsurancePercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChunkSize", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ChunkSize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAliveChunk", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxAliveChunk.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
