// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: canto/liquidstaking/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgLiquidStake struct {
	// token_amount is the amount of native token to be liquid staked.
	TokenAmount github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,1,opt,name=token_amount,json=tokenAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"token_amount"`
	// requester_address is the address of the user who requests the liquid
	// staking.
	RequesterAddress string `protobuf:"bytes,2,opt,name=requester_address,json=requesterAddress,proto3" json:"requester_address,omitempty"`
}

func (m *MsgLiquidStake) Reset()         { *m = MsgLiquidStake{} }
func (m *MsgLiquidStake) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidStake) ProtoMessage()    {}
func (*MsgLiquidStake) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{0}
}
func (m *MsgLiquidStake) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLiquidStake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLiquidStake.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLiquidStake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidStake.Merge(m, src)
}
func (m *MsgLiquidStake) XXX_Size() int {
	return m.Size()
}
func (m *MsgLiquidStake) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidStake.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidStake proto.InternalMessageInfo

func (m *MsgLiquidStake) GetRequesterAddress() string {
	if m != nil {
		return m.RequesterAddress
	}
	return ""
}

type MsgLiquidStakeResponse struct {
}

func (m *MsgLiquidStakeResponse) Reset()         { *m = MsgLiquidStakeResponse{} }
func (m *MsgLiquidStakeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidStakeResponse) ProtoMessage()    {}
func (*MsgLiquidStakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{1}
}
func (m *MsgLiquidStakeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLiquidStakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLiquidStakeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLiquidStakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidStakeResponse.Merge(m, src)
}
func (m *MsgLiquidStakeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLiquidStakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidStakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidStakeResponse proto.InternalMessageInfo

type MsgCancelLiquidStake struct {
	// requester_address is the address of the user who want to cancel the liquid
	// staking. If the chunk is already paired, it cannot be canceled.
	RequesterAddress string `protobuf:"bytes,1,opt,name=requester_address,json=requesterAddress,proto3" json:"requester_address,omitempty"`
}

func (m *MsgCancelLiquidStake) Reset()         { *m = MsgCancelLiquidStake{} }
func (m *MsgCancelLiquidStake) String() string { return proto.CompactTextString(m) }
func (*MsgCancelLiquidStake) ProtoMessage()    {}
func (*MsgCancelLiquidStake) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{2}
}
func (m *MsgCancelLiquidStake) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelLiquidStake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelLiquidStake.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelLiquidStake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelLiquidStake.Merge(m, src)
}
func (m *MsgCancelLiquidStake) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelLiquidStake) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelLiquidStake.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelLiquidStake proto.InternalMessageInfo

func (m *MsgCancelLiquidStake) GetRequesterAddress() string {
	if m != nil {
		return m.RequesterAddress
	}
	return ""
}

type MsgCancelLiquidStakeResponse struct {
}

func (m *MsgCancelLiquidStakeResponse) Reset()         { *m = MsgCancelLiquidStakeResponse{} }
func (m *MsgCancelLiquidStakeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelLiquidStakeResponse) ProtoMessage()    {}
func (*MsgCancelLiquidStakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{3}
}
func (m *MsgCancelLiquidStakeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelLiquidStakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelLiquidStakeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelLiquidStakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelLiquidStakeResponse.Merge(m, src)
}
func (m *MsgCancelLiquidStakeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelLiquidStakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelLiquidStakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelLiquidStakeResponse proto.InternalMessageInfo

type MsgLiquidUnstake struct {
	// number_of_chunks is the number of chunks to be unstaked.
	// The requester must have corresponding ls tokens to unstake.
	NumberOfChunks uint64 `protobuf:"varint,1,opt,name=number_of_chunks,json=numberOfChunks,proto3" json:"number_of_chunks,omitempty"`
	// requester_address is the address of the user who want to liquid unstaking.
	RequesterAddress string `protobuf:"bytes,2,opt,name=requester_address,json=requesterAddress,proto3" json:"requester_address,omitempty"`
}

func (m *MsgLiquidUnstake) Reset()         { *m = MsgLiquidUnstake{} }
func (m *MsgLiquidUnstake) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidUnstake) ProtoMessage()    {}
func (*MsgLiquidUnstake) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{4}
}
func (m *MsgLiquidUnstake) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLiquidUnstake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLiquidUnstake.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLiquidUnstake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidUnstake.Merge(m, src)
}
func (m *MsgLiquidUnstake) XXX_Size() int {
	return m.Size()
}
func (m *MsgLiquidUnstake) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidUnstake.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidUnstake proto.InternalMessageInfo

func (m *MsgLiquidUnstake) GetNumberOfChunks() uint64 {
	if m != nil {
		return m.NumberOfChunks
	}
	return 0
}

func (m *MsgLiquidUnstake) GetRequesterAddress() string {
	if m != nil {
		return m.RequesterAddress
	}
	return ""
}

type MsgLiquidUnstakeResponse struct {
}

func (m *MsgLiquidUnstakeResponse) Reset()         { *m = MsgLiquidUnstakeResponse{} }
func (m *MsgLiquidUnstakeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidUnstakeResponse) ProtoMessage()    {}
func (*MsgLiquidUnstakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{5}
}
func (m *MsgLiquidUnstakeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLiquidUnstakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLiquidUnstakeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLiquidUnstakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidUnstakeResponse.Merge(m, src)
}
func (m *MsgLiquidUnstakeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLiquidUnstakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidUnstakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidUnstakeResponse proto.InternalMessageInfo

type MsgInsuranceProvide struct {
	// validator_address is the address of the validator to provide insurance.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// requester_address is the address of the user who want to provide insurance.
	RequesterAddress string `protobuf:"bytes,2,opt,name=requester_address,json=requesterAddress,proto3" json:"requester_address,omitempty"`
	// token_amount is the amount of native token to be provided as insurance.
	TokenAmount github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,3,opt,name=token_amount,json=tokenAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"token_amount"`
	// fee_rate is the fee rate of the insurance.
	FeeRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=fee_rate,json=feeRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"fee_rate"`
}

func (m *MsgInsuranceProvide) Reset()         { *m = MsgInsuranceProvide{} }
func (m *MsgInsuranceProvide) String() string { return proto.CompactTextString(m) }
func (*MsgInsuranceProvide) ProtoMessage()    {}
func (*MsgInsuranceProvide) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{6}
}
func (m *MsgInsuranceProvide) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInsuranceProvide) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInsuranceProvide.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInsuranceProvide) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInsuranceProvide.Merge(m, src)
}
func (m *MsgInsuranceProvide) XXX_Size() int {
	return m.Size()
}
func (m *MsgInsuranceProvide) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInsuranceProvide.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInsuranceProvide proto.InternalMessageInfo

func (m *MsgInsuranceProvide) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *MsgInsuranceProvide) GetRequesterAddress() string {
	if m != nil {
		return m.RequesterAddress
	}
	return ""
}

type MsgInsuranceProvideResponse struct {
}

func (m *MsgInsuranceProvideResponse) Reset()         { *m = MsgInsuranceProvideResponse{} }
func (m *MsgInsuranceProvideResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInsuranceProvideResponse) ProtoMessage()    {}
func (*MsgInsuranceProvideResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{7}
}
func (m *MsgInsuranceProvideResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInsuranceProvideResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInsuranceProvideResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInsuranceProvideResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInsuranceProvideResponse.Merge(m, src)
}
func (m *MsgInsuranceProvideResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInsuranceProvideResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInsuranceProvideResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInsuranceProvideResponse proto.InternalMessageInfo

type MsgCancelInsuranceProvide struct {
	// id is the id of the insurance to be canceled.
	// Only pairing insurance can be canceled.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// requester_address is the address of the user who want to cancel the
	// insurance.
	RequesterAddress string `protobuf:"bytes,2,opt,name=requester_address,json=requesterAddress,proto3" json:"requester_address,omitempty"`
}

func (m *MsgCancelInsuranceProvide) Reset()         { *m = MsgCancelInsuranceProvide{} }
func (m *MsgCancelInsuranceProvide) String() string { return proto.CompactTextString(m) }
func (*MsgCancelInsuranceProvide) ProtoMessage()    {}
func (*MsgCancelInsuranceProvide) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{8}
}
func (m *MsgCancelInsuranceProvide) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelInsuranceProvide) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelInsuranceProvide.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelInsuranceProvide) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelInsuranceProvide.Merge(m, src)
}
func (m *MsgCancelInsuranceProvide) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelInsuranceProvide) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelInsuranceProvide.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelInsuranceProvide proto.InternalMessageInfo

func (m *MsgCancelInsuranceProvide) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgCancelInsuranceProvide) GetRequesterAddress() string {
	if m != nil {
		return m.RequesterAddress
	}
	return ""
}

type MsgCancelInsuranceProvideResponse struct {
}

func (m *MsgCancelInsuranceProvideResponse) Reset()         { *m = MsgCancelInsuranceProvideResponse{} }
func (m *MsgCancelInsuranceProvideResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelInsuranceProvideResponse) ProtoMessage()    {}
func (*MsgCancelInsuranceProvideResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{9}
}
func (m *MsgCancelInsuranceProvideResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelInsuranceProvideResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelInsuranceProvideResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelInsuranceProvideResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelInsuranceProvideResponse.Merge(m, src)
}
func (m *MsgCancelInsuranceProvideResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelInsuranceProvideResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelInsuranceProvideResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelInsuranceProvideResponse proto.InternalMessageInfo

type MsgDepositInsurance struct {
	// id is the id of the insurance to be refilled.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// requester_address is the address of the user who
	// want to deposit(= refill) the insurance.
	RequesterAddress string `protobuf:"bytes,2,opt,name=requester_address,json=requesterAddress,proto3" json:"requester_address,omitempty"`
	// token_amount is the amount of native token to be provided as insurance.
	TokenAmount github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,3,opt,name=token_amount,json=tokenAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"token_amount"`
}

func (m *MsgDepositInsurance) Reset()         { *m = MsgDepositInsurance{} }
func (m *MsgDepositInsurance) String() string { return proto.CompactTextString(m) }
func (*MsgDepositInsurance) ProtoMessage()    {}
func (*MsgDepositInsurance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{10}
}
func (m *MsgDepositInsurance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositInsurance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositInsurance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositInsurance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositInsurance.Merge(m, src)
}
func (m *MsgDepositInsurance) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositInsurance) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositInsurance.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositInsurance proto.InternalMessageInfo

func (m *MsgDepositInsurance) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgDepositInsurance) GetRequesterAddress() string {
	if m != nil {
		return m.RequesterAddress
	}
	return ""
}

type MsgDepositInsuranceResponse struct {
}

func (m *MsgDepositInsuranceResponse) Reset()         { *m = MsgDepositInsuranceResponse{} }
func (m *MsgDepositInsuranceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDepositInsuranceResponse) ProtoMessage()    {}
func (*MsgDepositInsuranceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{11}
}
func (m *MsgDepositInsuranceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositInsuranceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositInsuranceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositInsuranceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositInsuranceResponse.Merge(m, src)
}
func (m *MsgDepositInsuranceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositInsuranceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositInsuranceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositInsuranceResponse proto.InternalMessageInfo

type MsgWithdrawInsurance struct {
	// id is the id of the insurance to be withdrawn.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// requester_address is the address of the user who want to
	// withdraw the insurance.
	RequesterAddress string `protobuf:"bytes,2,opt,name=requester_address,json=requesterAddress,proto3" json:"requester_address,omitempty"`
}

func (m *MsgWithdrawInsurance) Reset()         { *m = MsgWithdrawInsurance{} }
func (m *MsgWithdrawInsurance) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawInsurance) ProtoMessage()    {}
func (*MsgWithdrawInsurance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{12}
}
func (m *MsgWithdrawInsurance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawInsurance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawInsurance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawInsurance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawInsurance.Merge(m, src)
}
func (m *MsgWithdrawInsurance) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawInsurance) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawInsurance.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawInsurance proto.InternalMessageInfo

func (m *MsgWithdrawInsurance) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgWithdrawInsurance) GetRequesterAddress() string {
	if m != nil {
		return m.RequesterAddress
	}
	return ""
}

type MsgWithdrawInsuranceResponse struct {
}

func (m *MsgWithdrawInsuranceResponse) Reset()         { *m = MsgWithdrawInsuranceResponse{} }
func (m *MsgWithdrawInsuranceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawInsuranceResponse) ProtoMessage()    {}
func (*MsgWithdrawInsuranceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{13}
}
func (m *MsgWithdrawInsuranceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawInsuranceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawInsuranceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawInsuranceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawInsuranceResponse.Merge(m, src)
}
func (m *MsgWithdrawInsuranceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawInsuranceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawInsuranceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawInsuranceResponse proto.InternalMessageInfo

type MsgWithdrawInsuranceFee struct {
	// id is the id of the insurance that accumulated fees to be withdrawn.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// requester_address is the address of the user who want to withdraw the
	// accumulated insurance fee.
	RequesterAddress string `protobuf:"bytes,2,opt,name=requester_address,json=requesterAddress,proto3" json:"requester_address,omitempty"`
}

func (m *MsgWithdrawInsuranceFee) Reset()         { *m = MsgWithdrawInsuranceFee{} }
func (m *MsgWithdrawInsuranceFee) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawInsuranceFee) ProtoMessage()    {}
func (*MsgWithdrawInsuranceFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{14}
}
func (m *MsgWithdrawInsuranceFee) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawInsuranceFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawInsuranceFee.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawInsuranceFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawInsuranceFee.Merge(m, src)
}
func (m *MsgWithdrawInsuranceFee) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawInsuranceFee) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawInsuranceFee.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawInsuranceFee proto.InternalMessageInfo

func (m *MsgWithdrawInsuranceFee) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgWithdrawInsuranceFee) GetRequesterAddress() string {
	if m != nil {
		return m.RequesterAddress
	}
	return ""
}

type MsgWithdrawInsuranceFeeResponse struct {
}

func (m *MsgWithdrawInsuranceFeeResponse) Reset()         { *m = MsgWithdrawInsuranceFeeResponse{} }
func (m *MsgWithdrawInsuranceFeeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawInsuranceFeeResponse) ProtoMessage()    {}
func (*MsgWithdrawInsuranceFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b50b1abccb5854, []int{15}
}
func (m *MsgWithdrawInsuranceFeeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawInsuranceFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawInsuranceFeeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawInsuranceFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawInsuranceFeeResponse.Merge(m, src)
}
func (m *MsgWithdrawInsuranceFeeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawInsuranceFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawInsuranceFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawInsuranceFeeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgLiquidStake)(nil), "canto.liquidstaking.v1.MsgLiquidStake")
	proto.RegisterType((*MsgLiquidStakeResponse)(nil), "canto.liquidstaking.v1.MsgLiquidStakeResponse")
	proto.RegisterType((*MsgCancelLiquidStake)(nil), "canto.liquidstaking.v1.MsgCancelLiquidStake")
	proto.RegisterType((*MsgCancelLiquidStakeResponse)(nil), "canto.liquidstaking.v1.MsgCancelLiquidStakeResponse")
	proto.RegisterType((*MsgLiquidUnstake)(nil), "canto.liquidstaking.v1.MsgLiquidUnstake")
	proto.RegisterType((*MsgLiquidUnstakeResponse)(nil), "canto.liquidstaking.v1.MsgLiquidUnstakeResponse")
	proto.RegisterType((*MsgInsuranceProvide)(nil), "canto.liquidstaking.v1.MsgInsuranceProvide")
	proto.RegisterType((*MsgInsuranceProvideResponse)(nil), "canto.liquidstaking.v1.MsgInsuranceProvideResponse")
	proto.RegisterType((*MsgCancelInsuranceProvide)(nil), "canto.liquidstaking.v1.MsgCancelInsuranceProvide")
	proto.RegisterType((*MsgCancelInsuranceProvideResponse)(nil), "canto.liquidstaking.v1.MsgCancelInsuranceProvideResponse")
	proto.RegisterType((*MsgDepositInsurance)(nil), "canto.liquidstaking.v1.MsgDepositInsurance")
	proto.RegisterType((*MsgDepositInsuranceResponse)(nil), "canto.liquidstaking.v1.MsgDepositInsuranceResponse")
	proto.RegisterType((*MsgWithdrawInsurance)(nil), "canto.liquidstaking.v1.MsgWithdrawInsurance")
	proto.RegisterType((*MsgWithdrawInsuranceResponse)(nil), "canto.liquidstaking.v1.MsgWithdrawInsuranceResponse")
	proto.RegisterType((*MsgWithdrawInsuranceFee)(nil), "canto.liquidstaking.v1.MsgWithdrawInsuranceFee")
	proto.RegisterType((*MsgWithdrawInsuranceFeeResponse)(nil), "canto.liquidstaking.v1.MsgWithdrawInsuranceFeeResponse")
}

func init() { proto.RegisterFile("canto/liquidstaking/v1/tx.proto", fileDescriptor_a8b50b1abccb5854) }

var fileDescriptor_a8b50b1abccb5854 = []byte{
	// 796 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x4b, 0x4f, 0xdb, 0x4a,
	0x14, 0xc7, 0x33, 0x01, 0xdd, 0xc7, 0x70, 0x2f, 0x0a, 0xb9, 0x88, 0x9b, 0xeb, 0xcb, 0x4d, 0x2e,
	0xae, 0xc4, 0x43, 0x80, 0x87, 0x34, 0x3c, 0x84, 0xba, 0x82, 0x20, 0x24, 0xa4, 0xa6, 0x8f, 0xa0,
	0x3e, 0xd4, 0x8d, 0x65, 0xe2, 0x89, 0x19, 0x25, 0xf1, 0x04, 0xcf, 0x38, 0xd0, 0x5d, 0xd5, 0x0f,
	0x50, 0xb5, 0xaa, 0xd4, 0x65, 0x97, 0x5d, 0x74, 0xd1, 0x7e, 0x80, 0x2e, 0xbb, 0x61, 0x89, 0xd4,
	0x4d, 0xd5, 0x05, 0xaa, 0xa0, 0x1f, 0xa4, 0xca, 0xd8, 0x4c, 0x93, 0x38, 0x71, 0x62, 0x41, 0x57,
	0x98, 0xf1, 0x39, 0xff, 0xf3, 0x3b, 0xe7, 0x30, 0x7f, 0x03, 0x33, 0x25, 0xc3, 0xe6, 0x14, 0x55,
	0xc9, 0x81, 0x4b, 0x4c, 0xc6, 0x8d, 0x0a, 0xb1, 0x2d, 0xd4, 0xc8, 0x22, 0x7e, 0xa4, 0xd5, 0x1d,
	0xca, 0x69, 0x72, 0x42, 0x04, 0x68, 0x6d, 0x01, 0x5a, 0x23, 0xab, 0x4c, 0x5a, 0x94, 0x5a, 0x55,
	0x8c, 0x8c, 0x3a, 0x41, 0x86, 0x6d, 0x53, 0x6e, 0x70, 0x42, 0x6d, 0xe6, 0x65, 0x29, 0xe3, 0x16,
	0xb5, 0xa8, 0x78, 0x44, 0xcd, 0x27, 0xef, 0x54, 0x7d, 0x01, 0xe0, 0x68, 0x81, 0x59, 0x37, 0x85,
	0xd6, 0x2e, 0x37, 0x2a, 0x38, 0x59, 0x84, 0x7f, 0x70, 0x5a, 0xc1, 0xb6, 0x6e, 0xd4, 0xa8, 0x6b,
	0xf3, 0x14, 0xf8, 0x1f, 0xcc, 0xfe, 0xbe, 0x89, 0x8e, 0x4f, 0x33, 0xb1, 0x2f, 0xa7, 0x99, 0x19,
	0x8b, 0xf0, 0x7d, 0x77, 0x4f, 0x2b, 0xd1, 0x1a, 0x2a, 0x51, 0x56, 0xa3, 0xcc, 0xff, 0xb1, 0xc8,
	0xcc, 0x0a, 0xe2, 0x8f, 0xeb, 0x98, 0x69, 0x79, 0x4a, 0xec, 0xe2, 0x88, 0x10, 0xd9, 0x10, 0x1a,
	0xc9, 0x79, 0x38, 0xe6, 0xe0, 0x03, 0x17, 0x33, 0x8e, 0x1d, 0xdd, 0x30, 0x4d, 0x07, 0x33, 0x96,
	0x8a, 0x37, 0x85, 0x8b, 0x09, 0xf9, 0x62, 0xc3, 0x3b, 0x57, 0x53, 0x70, 0xa2, 0x1d, 0xa9, 0x88,
	0x59, 0x9d, 0xda, 0x0c, 0xab, 0x79, 0x38, 0x5e, 0x60, 0x56, 0xde, 0xb0, 0x4b, 0xb8, 0xda, 0x8a,
	0xdc, 0x55, 0x1e, 0xf4, 0x90, 0x4f, 0xc3, 0xc9, 0x6e, 0x22, 0xb2, 0x08, 0x81, 0x09, 0x59, 0xfe,
	0x9e, 0xcd, 0x44, 0x81, 0x59, 0x98, 0xb0, 0xdd, 0xda, 0x1e, 0x76, 0x74, 0x5a, 0xd6, 0x4b, 0xfb,
	0xae, 0x5d, 0xf1, 0xf4, 0x87, 0x8b, 0xa3, 0xde, 0xf9, 0xed, 0x72, 0x5e, 0x9c, 0x46, 0xeb, 0x54,
	0x81, 0xa9, 0xce, 0x52, 0x12, 0xe3, 0x59, 0x1c, 0xfe, 0x55, 0x60, 0xd6, 0x8e, 0xcd, 0x5c, 0xa7,
	0xc9, 0x7a, 0xc7, 0xa1, 0x0d, 0x62, 0x8a, 0x5e, 0x1b, 0x46, 0x95, 0x98, 0x06, 0xa7, 0x81, 0x5e,
	0xe5, 0x0b, 0xbf, 0x40, 0x24, 0x9a, 0xc0, 0xe2, 0x87, 0xae, 0x60, 0xf1, 0x3b, 0xf0, 0xb7, 0x32,
	0xc6, 0xba, 0x63, 0x70, 0x9c, 0x1a, 0x16, 0x7a, 0x9a, 0xaf, 0x37, 0x3d, 0x80, 0xde, 0x16, 0x2e,
	0x15, 0x7f, 0x2d, 0x63, 0x5c, 0x34, 0x38, 0x56, 0xff, 0x83, 0xff, 0x76, 0x99, 0x87, 0x9c, 0xd7,
	0x43, 0xf8, 0x8f, 0x5c, 0x6b, 0x60, 0x68, 0xa3, 0x30, 0x4e, 0x4c, 0x7f, 0x63, 0x71, 0x62, 0x46,
	0xdb, 0xd2, 0x35, 0x38, 0xd5, 0x53, 0x59, 0x96, 0x7f, 0x03, 0xc4, 0xba, 0xb6, 0x70, 0x9d, 0x32,
	0xc2, 0x65, 0xd8, 0xa5, 0x2a, 0xff, 0x8c, 0x8d, 0xf8, 0x63, 0xec, 0xe4, 0x94, 0x7d, 0xec, 0x8a,
	0x2b, 0xf6, 0x80, 0xf0, 0x7d, 0xd3, 0x31, 0x0e, 0xaf, 0xa6, 0x0f, 0xff, 0xca, 0x05, 0x44, 0x65,
	0xd1, 0xfb, 0xf0, 0xef, 0x6e, 0xef, 0xb7, 0xf1, 0x25, 0xeb, 0x4e, 0xc1, 0x4c, 0x0f, 0xdd, 0x8b,
	0xd2, 0xd7, 0x9f, 0x8c, 0xc0, 0xa1, 0x02, 0xb3, 0x92, 0xaf, 0x00, 0x1c, 0x69, 0xb5, 0x94, 0x69,
	0xad, 0xbb, 0xcb, 0x6a, 0xed, 0xd6, 0xa4, 0x68, 0x83, 0xc5, 0xc9, 0x56, 0xd1, 0xd3, 0x4f, 0xdf,
	0x5e, 0xc6, 0xe7, 0xd4, 0x19, 0xd4, 0xd3, 0xe6, 0xfd, 0x33, 0xdd, 0xb3, 0x9e, 0xf7, 0x00, 0x8e,
	0x05, 0x1d, 0x6f, 0x21, 0xa4, 0x6c, 0x20, 0x5a, 0x59, 0x8e, 0x12, 0x2d, 0x51, 0x57, 0x05, 0xea,
	0x92, 0xaa, 0x85, 0xa0, 0x96, 0x44, 0xb6, 0xde, 0x46, 0xfc, 0x1a, 0xc0, 0x3f, 0x3b, 0xec, 0xb3,
	0xef, 0x90, 0xfc, 0x48, 0x65, 0x69, 0xd0, 0x48, 0x49, 0x99, 0x15, 0x94, 0xf3, 0xea, 0x5c, 0xff,
	0x81, 0xba, 0x3e, 0xce, 0x5b, 0x00, 0x13, 0x41, 0x5f, 0x0d, 0xa9, 0xdc, 0x19, 0xac, 0xe4, 0x22,
	0x04, 0x4b, 0xd2, 0x65, 0x41, 0xaa, 0xa9, 0x0b, 0x21, 0xa4, 0xe4, 0x22, 0x59, 0xaf, 0xfb, 0x5c,
	0x1f, 0x01, 0x9c, 0xe8, 0xe1, 0x6a, 0xd9, 0xbe, 0x6b, 0x0d, 0x80, 0xaf, 0x47, 0x4e, 0x91, 0xf8,
	0x37, 0x04, 0xfe, 0x8a, 0x9a, 0xeb, 0xff, 0xe7, 0x10, 0xec, 0xa2, 0x39, 0xf2, 0x80, 0x37, 0x86,
	0x8d, 0xbc, 0x33, 0x38, 0x74, 0xe4, 0x3d, 0xdd, 0x6c, 0x90, 0x91, 0x9b, 0x5e, 0xf2, 0x0f, 0xe8,
	0xe4, 0x3b, 0x00, 0xc7, 0x82, 0x0e, 0x18, 0x76, 0xe5, 0x02, 0xd1, 0xa1, 0x57, 0xae, 0xb7, 0x11,
	0xae, 0x08, 0x5e, 0xa4, 0x2e, 0x86, 0xf0, 0x1e, 0xfa, 0xd9, 0x2d, 0xc0, 0x1f, 0x00, 0x1c, 0xef,
	0xea, 0x9e, 0x28, 0x0a, 0xc5, 0x36, 0xc6, 0xca, 0x5a, 0xc4, 0x04, 0x49, 0xbe, 0x2e, 0xc8, 0x73,
	0x6a, 0x36, 0x12, 0xb9, 0x5e, 0xc6, 0x78, 0xf3, 0xee, 0xf1, 0x59, 0x1a, 0x9c, 0x9c, 0xa5, 0xc1,
	0xd7, 0xb3, 0x34, 0x78, 0x7e, 0x9e, 0x8e, 0x9d, 0x9c, 0xa7, 0x63, 0x9f, 0xcf, 0xd3, 0xb1, 0x47,
	0x6b, 0x2d, 0x5f, 0xb8, 0x7c, 0x53, 0x76, 0xf1, 0x16, 0xe6, 0x87, 0xd4, 0xa9, 0x78, 0xbf, 0xa1,
	0xc6, 0x2a, 0x3a, 0xea, 0xa8, 0x24, 0x3e, 0x7b, 0x7b, 0xbf, 0x88, 0xff, 0x6e, 0x73, 0xdf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xa1, 0xc1, 0xea, 0x71, 0x4c, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	LiquidStake(ctx context.Context, in *MsgLiquidStake, opts ...grpc.CallOption) (*MsgLiquidStakeResponse, error)
	CancelLiquidStake(ctx context.Context, in *MsgCancelLiquidStake, opts ...grpc.CallOption) (*MsgCancelLiquidStakeResponse, error)
	LiquidUnstake(ctx context.Context, in *MsgLiquidUnstake, opts ...grpc.CallOption) (*MsgLiquidUnstakeResponse, error)
	InsuranceProvide(ctx context.Context, in *MsgInsuranceProvide, opts ...grpc.CallOption) (*MsgInsuranceProvideResponse, error)
	CancelInsuranceProvide(ctx context.Context, in *MsgCancelInsuranceProvide, opts ...grpc.CallOption) (*MsgCancelInsuranceProvideResponse, error)
	DepositInsurance(ctx context.Context, in *MsgDepositInsurance, opts ...grpc.CallOption) (*MsgDepositInsuranceResponse, error)
	WithdrawInsurance(ctx context.Context, in *MsgWithdrawInsurance, opts ...grpc.CallOption) (*MsgWithdrawInsuranceResponse, error)
	// WithdrawInsuranceFee is used to withdraw the cumulated insurance fee.
	WithdrawInsuranceFee(ctx context.Context, in *MsgWithdrawInsuranceFee, opts ...grpc.CallOption) (*MsgWithdrawInsuranceFeeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) LiquidStake(ctx context.Context, in *MsgLiquidStake, opts ...grpc.CallOption) (*MsgLiquidStakeResponse, error) {
	out := new(MsgLiquidStakeResponse)
	err := c.cc.Invoke(ctx, "/canto.liquidstaking.v1.Msg/LiquidStake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelLiquidStake(ctx context.Context, in *MsgCancelLiquidStake, opts ...grpc.CallOption) (*MsgCancelLiquidStakeResponse, error) {
	out := new(MsgCancelLiquidStakeResponse)
	err := c.cc.Invoke(ctx, "/canto.liquidstaking.v1.Msg/CancelLiquidStake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) LiquidUnstake(ctx context.Context, in *MsgLiquidUnstake, opts ...grpc.CallOption) (*MsgLiquidUnstakeResponse, error) {
	out := new(MsgLiquidUnstakeResponse)
	err := c.cc.Invoke(ctx, "/canto.liquidstaking.v1.Msg/LiquidUnstake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InsuranceProvide(ctx context.Context, in *MsgInsuranceProvide, opts ...grpc.CallOption) (*MsgInsuranceProvideResponse, error) {
	out := new(MsgInsuranceProvideResponse)
	err := c.cc.Invoke(ctx, "/canto.liquidstaking.v1.Msg/InsuranceProvide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelInsuranceProvide(ctx context.Context, in *MsgCancelInsuranceProvide, opts ...grpc.CallOption) (*MsgCancelInsuranceProvideResponse, error) {
	out := new(MsgCancelInsuranceProvideResponse)
	err := c.cc.Invoke(ctx, "/canto.liquidstaking.v1.Msg/CancelInsuranceProvide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DepositInsurance(ctx context.Context, in *MsgDepositInsurance, opts ...grpc.CallOption) (*MsgDepositInsuranceResponse, error) {
	out := new(MsgDepositInsuranceResponse)
	err := c.cc.Invoke(ctx, "/canto.liquidstaking.v1.Msg/DepositInsurance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawInsurance(ctx context.Context, in *MsgWithdrawInsurance, opts ...grpc.CallOption) (*MsgWithdrawInsuranceResponse, error) {
	out := new(MsgWithdrawInsuranceResponse)
	err := c.cc.Invoke(ctx, "/canto.liquidstaking.v1.Msg/WithdrawInsurance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawInsuranceFee(ctx context.Context, in *MsgWithdrawInsuranceFee, opts ...grpc.CallOption) (*MsgWithdrawInsuranceFeeResponse, error) {
	out := new(MsgWithdrawInsuranceFeeResponse)
	err := c.cc.Invoke(ctx, "/canto.liquidstaking.v1.Msg/WithdrawInsuranceFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	LiquidStake(context.Context, *MsgLiquidStake) (*MsgLiquidStakeResponse, error)
	CancelLiquidStake(context.Context, *MsgCancelLiquidStake) (*MsgCancelLiquidStakeResponse, error)
	LiquidUnstake(context.Context, *MsgLiquidUnstake) (*MsgLiquidUnstakeResponse, error)
	InsuranceProvide(context.Context, *MsgInsuranceProvide) (*MsgInsuranceProvideResponse, error)
	CancelInsuranceProvide(context.Context, *MsgCancelInsuranceProvide) (*MsgCancelInsuranceProvideResponse, error)
	DepositInsurance(context.Context, *MsgDepositInsurance) (*MsgDepositInsuranceResponse, error)
	WithdrawInsurance(context.Context, *MsgWithdrawInsurance) (*MsgWithdrawInsuranceResponse, error)
	// WithdrawInsuranceFee is used to withdraw the cumulated insurance fee.
	WithdrawInsuranceFee(context.Context, *MsgWithdrawInsuranceFee) (*MsgWithdrawInsuranceFeeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) LiquidStake(ctx context.Context, req *MsgLiquidStake) (*MsgLiquidStakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiquidStake not implemented")
}
func (*UnimplementedMsgServer) CancelLiquidStake(ctx context.Context, req *MsgCancelLiquidStake) (*MsgCancelLiquidStakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelLiquidStake not implemented")
}
func (*UnimplementedMsgServer) LiquidUnstake(ctx context.Context, req *MsgLiquidUnstake) (*MsgLiquidUnstakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiquidUnstake not implemented")
}
func (*UnimplementedMsgServer) InsuranceProvide(ctx context.Context, req *MsgInsuranceProvide) (*MsgInsuranceProvideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsuranceProvide not implemented")
}
func (*UnimplementedMsgServer) CancelInsuranceProvide(ctx context.Context, req *MsgCancelInsuranceProvide) (*MsgCancelInsuranceProvideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelInsuranceProvide not implemented")
}
func (*UnimplementedMsgServer) DepositInsurance(ctx context.Context, req *MsgDepositInsurance) (*MsgDepositInsuranceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositInsurance not implemented")
}
func (*UnimplementedMsgServer) WithdrawInsurance(ctx context.Context, req *MsgWithdrawInsurance) (*MsgWithdrawInsuranceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawInsurance not implemented")
}
func (*UnimplementedMsgServer) WithdrawInsuranceFee(ctx context.Context, req *MsgWithdrawInsuranceFee) (*MsgWithdrawInsuranceFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawInsuranceFee not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_LiquidStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLiquidStake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LiquidStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.liquidstaking.v1.Msg/LiquidStake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LiquidStake(ctx, req.(*MsgLiquidStake))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelLiquidStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelLiquidStake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelLiquidStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.liquidstaking.v1.Msg/CancelLiquidStake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelLiquidStake(ctx, req.(*MsgCancelLiquidStake))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_LiquidUnstake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLiquidUnstake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LiquidUnstake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.liquidstaking.v1.Msg/LiquidUnstake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LiquidUnstake(ctx, req.(*MsgLiquidUnstake))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InsuranceProvide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInsuranceProvide)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InsuranceProvide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.liquidstaking.v1.Msg/InsuranceProvide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InsuranceProvide(ctx, req.(*MsgInsuranceProvide))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelInsuranceProvide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelInsuranceProvide)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelInsuranceProvide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.liquidstaking.v1.Msg/CancelInsuranceProvide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelInsuranceProvide(ctx, req.(*MsgCancelInsuranceProvide))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DepositInsurance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDepositInsurance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DepositInsurance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.liquidstaking.v1.Msg/DepositInsurance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DepositInsurance(ctx, req.(*MsgDepositInsurance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawInsurance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawInsurance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawInsurance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.liquidstaking.v1.Msg/WithdrawInsurance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawInsurance(ctx, req.(*MsgWithdrawInsurance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawInsuranceFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawInsuranceFee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawInsuranceFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.liquidstaking.v1.Msg/WithdrawInsuranceFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawInsuranceFee(ctx, req.(*MsgWithdrawInsuranceFee))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "canto.liquidstaking.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LiquidStake",
			Handler:    _Msg_LiquidStake_Handler,
		},
		{
			MethodName: "CancelLiquidStake",
			Handler:    _Msg_CancelLiquidStake_Handler,
		},
		{
			MethodName: "LiquidUnstake",
			Handler:    _Msg_LiquidUnstake_Handler,
		},
		{
			MethodName: "InsuranceProvide",
			Handler:    _Msg_InsuranceProvide_Handler,
		},
		{
			MethodName: "CancelInsuranceProvide",
			Handler:    _Msg_CancelInsuranceProvide_Handler,
		},
		{
			MethodName: "DepositInsurance",
			Handler:    _Msg_DepositInsurance_Handler,
		},
		{
			MethodName: "WithdrawInsurance",
			Handler:    _Msg_WithdrawInsurance_Handler,
		},
		{
			MethodName: "WithdrawInsuranceFee",
			Handler:    _Msg_WithdrawInsuranceFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "canto/liquidstaking/v1/tx.proto",
}

func (m *MsgLiquidStake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLiquidStake) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLiquidStake) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequesterAddress) > 0 {
		i -= len(m.RequesterAddress)
		copy(dAtA[i:], m.RequesterAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequesterAddress)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.TokenAmount.Size()
		i -= size
		if _, err := m.TokenAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgLiquidStakeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLiquidStakeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLiquidStakeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelLiquidStake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelLiquidStake) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelLiquidStake) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequesterAddress) > 0 {
		i -= len(m.RequesterAddress)
		copy(dAtA[i:], m.RequesterAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequesterAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelLiquidStakeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelLiquidStakeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelLiquidStakeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgLiquidUnstake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLiquidUnstake) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLiquidUnstake) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequesterAddress) > 0 {
		i -= len(m.RequesterAddress)
		copy(dAtA[i:], m.RequesterAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequesterAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.NumberOfChunks != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NumberOfChunks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgLiquidUnstakeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLiquidUnstakeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLiquidUnstakeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgInsuranceProvide) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInsuranceProvide) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInsuranceProvide) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.FeeRate.Size()
		i -= size
		if _, err := m.FeeRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.TokenAmount.Size()
		i -= size
		if _, err := m.TokenAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.RequesterAddress) > 0 {
		i -= len(m.RequesterAddress)
		copy(dAtA[i:], m.RequesterAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequesterAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInsuranceProvideResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInsuranceProvideResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInsuranceProvideResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelInsuranceProvide) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelInsuranceProvide) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelInsuranceProvide) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequesterAddress) > 0 {
		i -= len(m.RequesterAddress)
		copy(dAtA[i:], m.RequesterAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequesterAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelInsuranceProvideResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelInsuranceProvideResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelInsuranceProvideResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDepositInsurance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositInsurance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositInsurance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TokenAmount.Size()
		i -= size
		if _, err := m.TokenAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.RequesterAddress) > 0 {
		i -= len(m.RequesterAddress)
		copy(dAtA[i:], m.RequesterAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequesterAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgDepositInsuranceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositInsuranceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositInsuranceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawInsurance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawInsurance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawInsurance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequesterAddress) > 0 {
		i -= len(m.RequesterAddress)
		copy(dAtA[i:], m.RequesterAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequesterAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawInsuranceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawInsuranceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawInsuranceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawInsuranceFee) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawInsuranceFee) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawInsuranceFee) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequesterAddress) > 0 {
		i -= len(m.RequesterAddress)
		copy(dAtA[i:], m.RequesterAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequesterAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawInsuranceFeeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawInsuranceFeeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawInsuranceFeeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgLiquidStake) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TokenAmount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.RequesterAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgLiquidStakeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelLiquidStake) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RequesterAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCancelLiquidStakeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgLiquidUnstake) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NumberOfChunks != 0 {
		n += 1 + sovTx(uint64(m.NumberOfChunks))
	}
	l = len(m.RequesterAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgLiquidUnstakeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgInsuranceProvide) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RequesterAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.TokenAmount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.FeeRate.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgInsuranceProvideResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelInsuranceProvide) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.RequesterAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCancelInsuranceProvideResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDepositInsurance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.RequesterAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.TokenAmount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgDepositInsuranceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdrawInsurance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.RequesterAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawInsuranceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdrawInsuranceFee) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.RequesterAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawInsuranceFeeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgLiquidStake) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLiquidStake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLiquidStake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequesterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequesterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLiquidStakeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLiquidStakeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLiquidStakeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelLiquidStake) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelLiquidStake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelLiquidStake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequesterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequesterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelLiquidStakeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelLiquidStakeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelLiquidStakeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLiquidUnstake) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLiquidUnstake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLiquidUnstake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumberOfChunks", wireType)
			}
			m.NumberOfChunks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumberOfChunks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequesterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequesterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLiquidUnstakeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLiquidUnstakeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLiquidUnstakeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInsuranceProvide) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInsuranceProvide: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInsuranceProvide: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequesterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequesterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInsuranceProvideResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInsuranceProvideResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInsuranceProvideResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelInsuranceProvide) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelInsuranceProvide: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelInsuranceProvide: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequesterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequesterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelInsuranceProvideResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelInsuranceProvideResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelInsuranceProvideResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositInsurance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositInsurance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositInsurance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequesterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequesterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositInsuranceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositInsuranceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositInsuranceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawInsurance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawInsurance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawInsurance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequesterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequesterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawInsuranceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawInsuranceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawInsuranceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawInsuranceFee) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawInsuranceFee: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawInsuranceFee: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequesterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequesterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawInsuranceFeeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawInsuranceFeeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawInsuranceFeeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
